### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [wisp-forest/lavender-md#1]
![image](https://github.com/wisp-forest/lavender-md/assets/155424398/0b496b4a-46ed-4701-b5f7-4f68b95cb2db)

**Comment by BasiqueEvangelist** [comment]
...how is this related to lavender-md? This is (possibly) an [owo-lib](https://github.com/wisp-forest/owo-lib/) issue, which is most likely hidden in mod menu because it is marked as a library
